name: "Terraform plan apply"

on:
    push:
        branches: ["main"]

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}       

jobs:
    terraform-plan:
        name: Terraform plan
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Install latest version of terraform CLI
              uses: hashicorp/setup-terraform@v3
        
            - name: Initialize terraform directory
              run: terraform init

            - name: Generate execution plan
              run: terraform plan -out=tfplan

            - name: Upload the artifact
              uses: actions/upload-artifact@v4
              with:
                name: terraform-plan
                path: tfplan
    
    terraform-apply:
        name: terraform-apply
        needs: terraform-plan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            
            - name: Login to Azure
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Install terraform latest version
              uses: hashicorp/setup-terraform@v3

            - name: Initialize terraform directory
              run: terraform init

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: terraform-plan
            
            - name: Terraform Apply
              run: terraform apply -auto-approve terraform-plan