name: "Terraform test"

on:
  push:
    branches: ["main"]

jobs:
  terraform-test:
    name: Terraform-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to github actions
        uses: actions/checkout@v4

      - name: Install latest version of terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Initialize terraform directory
        run: terraform init

      - name: Check formating of terraform files
        run: terraform fmt -check -recursive

      - name: Validate terraform files
        run: terrform validate