name: 'Terraform Plan Apply'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

      # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Login to Azure
      run: |
        echo "##[set-env name=ARM_CLIENT_ID]::${{ secrets.AZURE_CLIENT_ID }}"
        echo "##[set-env name=ARM_CLIENT_SECRET]::${{ secrets.AZURE_CLIENT_SECRET }}"
        echo "##[set-env name=ARM_TENANT_ID]::${{ secrets.AZURE_TENANT_ID }}"
        echo "##[set-env name=ARM_SUBSCRIPTION_ID]::${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Generate execution plan
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve

